version: "3.9"
services:
  frontend-prod:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    container_name: frontend-prod
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
     - network
networks:
 network: